## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.1
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly
env: PYTHON=3.6
dist: xenial
## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    update: true
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3-pip
before_script: # homebrew for mac
   # install SpineInterface.jl
   # TODO: this is building Conda, PyCall and SpineInterface twice... Maybe we don't need Pkg.build("SpineInterface")?
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(path=pwd())); Pkg.build("SpineInterface"); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
after_success: skip
