## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux

julia:
  - 1.1
notifications:
  email: false
git:
  depth: 99999999

env: PYTHON=3.6
  global:
    - DISABLE_AMEND_COVERAGE_FROM_SRC=yes

dist: xenial

addons:
  apt: # apt-get for linux
    update: true
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3-pip

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate()'
  - /home/travis/.julia/conda/3/bin/python -m pip install --user 'git+https://github.com/Spine-project/Spine-Database-API'
  - julia --project=docs/ docs/make.jl

after_success:
  - julia -e 'using Pkg; Pkg.test("SpineInterface", coverage=true)'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
